version: 2.1

orbs:
  python: circleci/python@1.3.0
  postgres: circleci/postgresql@1.1.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use the appropriate Python version
    steps:
      - checkout
      - setup_remote_docker  # Add this if your tests require Docker
      - python/install-packages:
          pkg-manager: pip
      - postgres/install
      - postgres/init_db:  # Initialize the database
          db_name: testdb
          db_user: circleci
      - run:
          name: Run tests
          command: |
            export FLASK_ENV=testing
            export DB_NAME=testdb
            export DB_USER=circleci
            export DB_PASSWORD=""
            export DB_HOST=localhost
            export DB_PORT=5432
            # Add any other necessary environment variables here
            # Run your test command
            python -m unittest discover tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
