version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run Tests with Coverage
          command: |
            coverage run -m unittest discover
            

      - run:
          name: Debug .coveralls.yml
          command: |
            cat .coveralls.yml
            

      - run:
          name: Upload Coverage to Coveralls
          command: |
            coveralls