version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: Print current directory
          command: |
            pwd
      - run:
          name: List files in the directory
          command: ls -la

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-dev libpq-dev  # Install PostgreSQL dependencies
            pip install -r requirements.txt

      - run:
          name: Set up database
          command: |
            python -c "from models import initialize_database; initialize_database('$DB_USER', '$DB_PASSWORD', '$DB_NAME', '$FLASK_ENV')"

      - run:
          name: Run tests
          command: |
            python -m unittest discover -s tests/
