version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    services:
      - postgresql
    environment:
      POSTGRES_USER: monicah
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: phuier@200
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

