version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          FLASK_ENV: testing
          DB_NAME: circle_test
          DB_USER: postgres
          DB_PASSWORD: ""
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: 1
          # Set any other necessary environment variables here, such as register_name and owner
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: pip install -r requirements.txt  # Install your project's dependencies
      - run:
          name: Create circleci user
          command: |
            psql -U postgres -c "CREATE ROLE circleci WITH LOGIN PASSWORD '';"
      - run:
          name: Initialize database
          command: |
            python -c "from run import create_app; app = create_app(); app.app_context().push(); from models import initialize_database; initialize_database()"
      - run:
          name: Run tests
          command: |
            # Run your test command, e.g., pytest or python -m unittest
            pytest tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
