# .circleci/config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    environment:
      # Set environment variables for database connection
      DATABASE_HOST: "127.0.0.1"
      DATABASE_PORT: 5433
      DATABASE_NAME: testdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: phuier@200

    steps:
      - checkout


      # Install PostgreSQL client
      - run:
          name: Install PostgreSQL client
          command: sudo apt-get update && sudo apt-get install postgresql-client

      # Install psycopg2
      - run:
          name: Install psycopg2
          command: pip install psycopg2
      - run:
          name: Install dotenv
          command: pip install python-dotenv
      - run:
          name: Install Flask
          command: pip install Flask bcrypt jwt  validate_email

      # Run your Python tests
      - run:
          name: Run Python tests
          command: python tests/test_app.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

