version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: Print current directory
          command: |
            pwd
      - run:
          name: List files in the directory
          command: ls -la

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-dev libpq-dev  # Install PostgreSQL dependencies
            pip install -r requirements.txt
      - run:
          name: Check PostgreSQL service status
          command: |
            sudo service postgresql status
            
      

      - run:
          name: Set up database
          command: python run.py

      - run:
          name: Run tests
          command: |
            python -m unittest discover -s tests/
