version: 2.1

jobs:
  build:

    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@localhost:5432/testdb

    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y postgresql-client python3-pip
      - run: pip3 install -r requirements.txt
      - run: python3 run.py
      - run: python3 tests/test-app.py

