# .circleci/config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Install PostgreSQL client
      - run:
          name: Install PostgreSQL client
          command: sudo apt-get update && sudo apt-get install postgresql-client

      # Install psycopg2
      - run:
          name: Install psycopg2
          command: pip install psycopg2

      # Run your Python tests
      - run:
          name: Run Python tests
          command: python test_my_app.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

