version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout


      - run:
          name: Install dependencies
          command: |
            sudo apt-get install python3-dev libpq-dev  # Install PostgreSQL dependencies
            pip install -r requirements.txt


      - run:
          name: Start PostgreSQL Service
          command: |
            sudo service postgresql stop
            sudo service postgresql start


      - run:
          name: Set up database
          command: |
            python -c "from models import initialize_database; initialize_database()"


      - run:
          name: Run tests
          command: |
            python -m unittest discover -s tests/

