version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Wait for PostgresSQL to start
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client
            until pg_isready -h localhost -p 5432; do sleep 1; done

      - run:
          name: Run Tests with Coverage
          command: |
            coverage run -m unittest discover
            

      - run:
          name: Debug .coveralls.yml
          command: |
            cat .coveralls.yml
            

      - run:
          name: Upload Coverage to Coveralls
          command: |
            coveralls