version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Set FLASK_ENV
          command: echo "FLASK_ENV=testing" >> $BASH_ENV


      - run:
          name: Run Tests with Coverage
          command: |
            source $BASH_ENV  # Source the environment variables
            coverage run -m unittest discover
            

      - run:
          name: Debug .coveralls.yml
          command: |
            cat .coveralls.yml
            

      - run:
          name: Upload Coverage to Coveralls
          command: |
            coveralls