version: 2.1

jobs:
  build:

    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/testdb

    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client python3-pip  # Install PostgreSQL client and Python3 pip
      - run: whoami
      - run: |
          sudo -u postgres psql -c "CREATE ROLE circleci WITH LOGIN PASSWORD 11111;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO circleci;"
      - run: pip3 install -r requirements.txt # Install psycopg2 for Python PostgreSQL interaction
      - run: python3 models.py  # Run your database initialization script
        # Run unittest
      - run: python3 -m unittest discover
