version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          FLASK_ENV: testing
          DB_NAME: circle_test
          DB_USER: postgres
          DB_PASSWORD: ""
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: 1
          # Set any other necessary environment variables here, such as register_name and owner
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: pip install -r requirements.txt  # Install your project's dependencies
      - run:
          name: Install dockerize
          command: |
           sudo apt-get update
           sudo apt-get install -y wget
           wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
           sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
           rm dockerize-linux-amd64-v0.6.1.tar.gz
      - run:
         name: Wait for PostgreSQL
         command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Initialize database
          command: |
            python -c "from run import create_app; app = create_app(); app.app_context().push(); from models import initialize_database; initialize_database()"
      - run:
          name: Run tests
          command: |
            # Run your test command, e.g., pytest or python -m unittest
            python -m unittest discover -s tests/
      - run:
          name: Run Tests with Coverage
          command: |
            coverage run -m unittest discover

      - run:
          name: Debug .coveralls.yml
          command: |
            cat .coveralls.yml

      - run:
          name: Upload Coverage to Coveralls
          command: |
            coveralls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
